# Generated by Django 6.1 on 2026-08-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('published_date', models.DateField()),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
